EXCLUDE_VERSIONS=3.14.12.5
# Temporally removed to speed up
EXCLUDE_ARCHS += eldk

include ${EPICS_ENV_PATH}/module.Makefile

PROJECT=IcePAP

AUTO_DEPENDENCIES = NO
USR_DEPENDENCIES += axisCore,10.2.0


SOURCES = \
  IcePAP/src/IcePAPAxis.cpp \
  IcePAP/src/IcePAPController.cpp \
  IcePAP/src/IcePAPMain.cpp

TEMPLATES = -none-

#MISCS = \
