include ${EPICS_ENV_PATH}/module.Makefile

# Temporally removed to speed up 
EXCLUDE_ARCHS += eldk

SOURCES = \
  IcePAPApp/src/IcePAPAxis.cpp \
  IcePAPApp/src/IcePAPController.cpp \
  IcePAPApp/src/IcePAPMain.cpp





#TEMPLATES = \
#  ecmcApp/Db/ecmcController.template \
#  ecmcApp/Db/ecmc.template \
#  ecmcApp/Db/ecmc-extra.template

